"""remove assembly versions

Revision ID: 3c37170e422f
Revises: 5a635b230eb8
Create Date: 2025-06-03 12:47:39.513934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c37170e422f'
down_revision: Union[str, None] = '5a635b230eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assembly_versions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assembly_versions',
    sa.Column('assembly_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assembly_version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.assembly_id'], name='assembly_versions_assembly_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assembly_id', name='assembly_versions_pkey')
    )
    # ### end Alembic commands ###
