"""add partner_sales_channels

Revision ID: 47dc7a1f9531
Revises: 73bce4dc410e
Create Date: 2025-07-01 08:34:46.821000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47dc7a1f9531'
down_revision: Union[str, None] = '73bce4dc410e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_sales_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fes_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.partner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner_sales_channels')
    # ### end Alembic commands ###
