"""all partner cutoffs required

Revision ID: 493bb38d2ed4
Revises: cfffbcaaf1e0
Create Date: 2025-06-09 18:29:31.928473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493bb38d2ed4'
down_revision: Union[str, None] = 'cfffbcaaf1e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partners', 'recipe_update_cutoff_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('partners', 'recipe_delete_cutoff_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('partners', 'max_assemblies_per_recipe',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partners', 'max_assemblies_per_recipe',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('partners', 'recipe_delete_cutoff_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('partners', 'recipe_update_cutoff_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
