"""add partner assembly option tables

Revision ID: 5a635b230eb8
Revises: 69085d3f1d6b
Create Date: 2025-05-30 14:01:07.262320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a635b230eb8'
down_revision: Union[str, None] = '69085d3f1d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assembly_packaging_options',
    sa.Column('assembly_packaging_option_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assembly_packaging_option_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('assembly_packaging_option_id')
    )
    op.create_table('partner_assembly_packaging_options',
    sa.Column('partner_id', sa.String(length=8), nullable=False),
    sa.Column('assembly_packaging_option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assembly_packaging_option_id'], ['assembly_packaging_options.assembly_packaging_option_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.partner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner_id', 'assembly_packaging_option_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner_assembly_packaging_options')
    op.drop_table('assembly_packaging_options')
    # ### end Alembic commands ###
