"""add idempotency_keys table

Revision ID: 69085d3f1d6b
Revises: 752e206da48c
Create Date: 2025-05-30 08:33:02.303010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69085d3f1d6b'
down_revision: Union[str, None] = '752e206da48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('idempotent_action', sa.String(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key', 'idempotent_action')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
