"""update brands to partner_brands table with fes_name

Revision ID: 73bce4dc410e
Revises: 7cd1b2cf7ea2
Create Date: 2025-06-30 16:29:48.368549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73bce4dc410e'
down_revision: Union[str, None] = '7cd1b2cf7ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fes_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.partner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('partner_id', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='brand_pkey')
    )
    op.drop_table('partner_brands')
    # ### end Alembic commands ###
