"""add assembly tables

Revision ID: 752e206da48c
Revises: 34d124c7aefd
Create Date: 2025-05-22 15:01:00.646762

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '752e206da48c'
down_revision: str | None = '34d124c7aefd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assemblies',
    sa.Column('assembly_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.String(length=8), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.partner_id'], ),
    sa.PrimaryKeyConstraint('assembly_id')
    )
    op.create_table('assembly_data_sources',
    sa.Column('assembly_id', sa.UUID(), nullable=False),
    sa.Column('culops_assembly_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.assembly_id'], ),
    sa.PrimaryKeyConstraint('assembly_id')
    )
    op.create_index(op.f('ix_assembly_data_sources_culops_assembly_id'), 'assembly_data_sources', ['culops_assembly_id'], unique=False)
    op.create_table('assembly_versions',
    sa.Column('assembly_id', sa.UUID(), nullable=False),
    sa.Column('assembly_version_number', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.assembly_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assembly_id')
    )
    op.alter_column('pantry_states', 'items_available_from',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('pantry_states', 'items_available_until',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pantry_states', 'items_available_until',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('pantry_states', 'items_available_from',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_table('assembly_versions')
    op.drop_index(op.f('ix_assembly_data_sources_culops_assembly_id'), table_name='assembly_data_sources')
    op.drop_table('assembly_data_sources')
    op.drop_table('assemblies')
    # ### end Alembic commands ###
