"""add culops_product_sku to the recipe_data_sources table

Revision ID: 7cd1b2cf7ea2
Revises: 27adbd86857b
Create Date: 2025-06-30 10:55:36.586529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd1b2cf7ea2'
down_revision: Union[str, None] = '27adbd86857b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_data_sources', sa.Column('culops_product_sku', sa.String(), nullable=False))
    op.create_index(op.f('ix_recipe_data_sources_culops_product_sku'), 'recipe_data_sources', ['culops_product_sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_data_sources_culops_product_sku'), table_name='recipe_data_sources')
    op.drop_column('recipe_data_sources', 'culops_product_sku')
    # ### end Alembic commands ###
