"""add recipe tables

Revision ID: cfffbcaaf1e0
Revises: 3c37170e422f
Create Date: 2025-06-09 15:22:08.183025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfffbcaaf1e0'
down_revision: Union[str, None] = '3c37170e422f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_packaging_configuration_tags',
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('culops_tag_type', sa.Enum('badge_tag_list', 'campaign_tag_list', name='partnerpackagingconfigurationtag'), nullable=False),
    sa.Column('partner_id', sa.String(length=8), nullable=False),
    sa.Column('culops_tag_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.partner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'culops_tag_type', 'partner_id')
    )
    op.create_table('partner_recipe_constraint_tags',
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('culops_tag_type', sa.Enum('badge_tag_list', 'campaign_tag_list', name='partnerrecipeconstrainttag'), nullable=False),
    sa.Column('partner_id', sa.String(length=8), nullable=False),
    sa.Column('culops_tag_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.partner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'culops_tag_type', 'partner_id')
    )
    op.create_table('partner_recipe_plans',
    sa.Column('partner_recipe_plan_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('partner_id', sa.String(length=8), nullable=True),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.partner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner_recipe_plan_id')
    )
    op.create_table('recipes',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.String(length=8), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.partner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_table('recipe_data_sources',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('culops_recipe_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_index(op.f('ix_recipe_data_sources_culops_recipe_id'), 'recipe_data_sources', ['culops_recipe_id'], unique=False)
    op.create_table('recipe_plan_data_sources',
    sa.Column('partner_recipe_plan_id', sa.Integer(), nullable=False),
    sa.Column('cabinet_plan_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['partner_recipe_plan_id'], ['partner_recipe_plans.partner_recipe_plan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner_recipe_plan_id')
    )
    op.create_index(op.f('ix_recipe_plan_data_sources_cabinet_plan_id'), 'recipe_plan_data_sources', ['cabinet_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_plan_data_sources_cabinet_plan_id'), table_name='recipe_plan_data_sources')
    op.drop_table('recipe_plan_data_sources')
    op.drop_index(op.f('ix_recipe_data_sources_culops_recipe_id'), table_name='recipe_data_sources')
    op.drop_table('recipe_data_sources')
    op.drop_table('recipes')
    op.drop_table('partner_recipe_plans')
    op.drop_table('partner_recipe_constraint_tags')
    op.drop_table('partner_packaging_configuration_tags')
    # ### end Alembic commands ###
