"""remove vendor_name from pantry_items table

Revision ID: ed6ea01230ed
Revises: db44426cfac1
Create Date: 2025-08-26 11:14:11.028468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6ea01230ed'
down_revision: Union[str, None] = 'db44426cfac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pantry_items', 'vendor_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pantry_items', sa.Column('vendor_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
