from typing import Protocol

from src.api.routes.v1.models import RecipeTags
from src.services.models.partner import Brand, CostMarkup, Partner, SalesChannel


class PartnerServiceInterface(Protocol):
    @property
    def partner_id(self) -> str: ...

    def validate_partner_id(self) -> bool: ...

    def get_partner(self) -> Partner: ...

    def get_partner_cost_markups(self) -> list[CostMarkup]: ...

    def get_partner_assembly_packaging_options(self) -> list[str]: ...

    def get_branding(self) -> list[Brand]: ...

    def map_tag_ids_to_values(self, recipe_tags: RecipeTags) -> tuple[list[str], list[str]]: ...

    def validate_tags(self, tags: RecipeTags) -> bool: ...

    def get_sales_channels(self) -> list[SalesChannel]: ...
