from typing import Protocol

from src.services.models.partner import Brand, CostMarkup, Partner, PartnerRecipePlanMap, SalesChannel
from src.services.models.recipe import PackagingConfigurationTag, RecipeConstraintTag


class PartnerRepoInterface(Protocol):
    def find_partner_id(self, partner_id: str) -> bool: ...

    def get_partner_by_id(self, partner_id: str) -> Partner: ...

    def get_partner_cost_markups(self, partner_id: str) -> list[CostMarkup]: ...

    def get_partner_assembly_packaging_options(self, partner_id: str) -> list[str]: ...

    def get_partner_recipe_plan_maps(self, partner_id: str) -> list[PartnerRecipePlanMap]: ...

    def get_partner_recipe_constraint_tags(self, partner_id: str) -> list[RecipeConstraintTag]: ...

    def get_partner_packaging_configuration_tags(self, partner_id: str) -> list[PackagingConfigurationTag]: ...

    def get_recipe_create_cutoff_days(self, partner_id: str) -> int: ...

    def get_recipe_update_cutoff_days(self, partner_id: str) -> int: ...

    def get_recipe_delete_cutoff_days(self, partner_id: str) -> int: ...

    def get_branding(self, partner_id: str) -> list[Brand]: ...

    def get_sales_channels(self, partner_id: str) -> list[SalesChannel]: ...
